import { StyleOption } from "./types";

export const STYLES_DATA: StyleOption[] = [
  {
    id: "romantic",
    name: "Romantic",
    icon: "❤️",
    description: "Heartfelt, deep, and beautifully expressive love statements.",
    color: "from-pink-500 to-rose-600",
    bgGradient: "bg-gradient-to-br from-pink-50 to-rose-100 dark:from-pink-950/20 dark:to-rose-900/20",
  },
  {
    id: "flirty",
    name: "Flirty",
    icon: "😉",
    description: "Playful, charming, teasing, and filled with sparks.",
    color: "from-amber-400 to-pink-500",
    bgGradient: "bg-gradient-to-br from-amber-50 to-pink-100 dark:from-amber-950/20 dark:to-pink-900/20",
  },
  {
    id: "funny",
    name: "Funny",
    icon: "😂",
    description: "Witty, goofy, and humorous takes on modern relationships.",
    color: "from-yellow-400 to-orange-500",
    bgGradient: "bg-gradient-to-br from-yellow-50 to-orange-100 dark:from-yellow-950/20 dark:to-orange-900/20",
  },
  {
    id: "cute",
    name: "Cute",
    icon: "🥰",
    description: "Sweet, adorable, and extremely cozy little whispers.",
    color: "from-rose-400 to-pink-400",
    bgGradient: "bg-gradient-to-br from-rose-50 to-pink-100 dark:from-rose-950/20 dark:to-pink-900/20",
  },
  {
    id: "deep",
    name: "Deep Emotional",
    icon: "💌",
    description: "Soulful, vulnerable, and intensely passionate true devotion.",
    color: "from-purple-600 to-indigo-700",
    bgGradient: "bg-gradient-to-br from-purple-50 to-indigo-100 dark:from-purple-950/20 dark:to-indigo-900/20",
  },
  {
    id: "apology",
    name: "Apology",
    icon: "🙏",
    description: "Sincere, humble, and affectionate words to make things right.",
    color: "from-blue-500 to-indigo-500",
    bgGradient: "bg-gradient-to-br from-blue-50 to-indigo-100 dark:from-blue-950/20 dark:to-indigo-900/20",
  },
  {
    id: "anniversary",
    name: "Anniversary",
    icon: "🎉",
    description: "Celebrate milestones, shared moments, and growing together.",
    color: "from-emerald-500 to-teal-600",
    bgGradient: "bg-gradient-to-br from-emerald-50 to-teal-100 dark:from-emerald-950/20 dark:to-teal-900/20",
  },
  {
    id: "morning",
    name: "Good Morning",
    icon: "☀️",
    description: "Bright, warm, and cheerful thoughts to greet their day.",
    color: "from-amber-500 to-orange-500",
    bgGradient: "bg-gradient-to-br from-amber-50 to-orange-100 dark:from-amber-950/20 dark:to-orange-900/20",
  },
  {
    id: "night",
    name: "Good Night",
    icon: "🌙",
    description: "Cozy, peaceful, and dreamy lullabies for sweet thoughts.",
    color: "from-indigo-600 to-slate-800",
    bgGradient: "bg-gradient-to-br from-indigo-50 to-slate-200 dark:from-indigo-950/20 dark:to-slate-900/20",
  },
  {
    id: "distance",
    name: "Long Distance",
    icon: "✈️",
    description: "Bridge the distance with words that count down the days.",
    color: "from-cyan-500 to-blue-600",
    bgGradient: "bg-gradient-to-br from-cyan-50 to-blue-100 dark:from-cyan-950/20 dark:to-blue-900/20",
  },
  {
    id: "poetry",
    name: "Poetry",
    icon: "✍️",
    description: "Rhythmic, metaphoric stanzas with rich romantic visual imagery.",
    color: "from-fuchsia-500 to-purple-600",
    bgGradient: "bg-gradient-to-br from-fuchsia-50 to-purple-100 dark:from-fuchsia-950/20 dark:to-purple-900/20",
  },
  {
    id: "shayari",
    name: "Shayari",
    icon: "🌹",
    description: "Urdu ghazal tone couplets filled with sheer romantic passion.",
    color: "from-red-500 to-rose-700",
    bgGradient: "bg-gradient-to-br from-red-50 to-rose-100 dark:from-red-950/20 dark:to-rose-900/20",
  },
  {
    id: "heartfelt",
    name: "Heartfelt",
    icon: "💖",
    description: "Simple, honest, and loving appreciation for being in your life.",
    color: "from-rose-500 to-pink-600",
    bgGradient: "bg-gradient-to-br from-rose-50 to-pink-100 dark:from-rose-950/20 dark:to-pink-900/20",
  },
  {
    id: "friendly",
    name: "Friendly",
    icon: "😊",
    description: "Warm, supportive, caring love with relaxed and low pressure vibes.",
    color: "from-teal-400 to-emerald-500",
    bgGradient: "bg-gradient-to-br from-teal-50 to-emerald-100 dark:from-teal-950/20 dark:to-emerald-900/20",
  },
];
